apiVersion: v1
kind: List
items:
- apiVersion: hive.openshift.io/v1
  kind: ClusterPool
  metadata:
    name: {{ hive_cluster_name }}-pool
    namespace: {{ hive_claim_ns|default("rhods") }}
  spec:
    baseDomain: {{ aws_domain|default("rhods.ccitredhat.com") }}
    imageSetRef:
      name: rhods-imageset-ocp-{{ ocp_version }} # see line 99
    inventory:
      - name: {{ hive_cluster_name }}-conf # see line 71
    platform:
      openstack:
        cloud: {{ osp_cloud_name|default("openstack") }}
        credentialsSecretRef:
          name: {{ hive_cluster_name }}-cred # see line 90
    installConfigSecretTemplateRef:
      name: {{ hive_cluster_name }}-sec # see line 30
    size: 1
    maxSize: 1
    maxConcurrent: 1
    runningCount: 1
    skipMachinePools: true
- apiVersion: v1
  kind: Secret
  metadata:
    name: {{ hive_cluster_name }}-sec
    namespace: {{ hive_claim_ns|default("rhods") }}
  type: Opaque
  stringData:
    install-config.yaml: |
      apiVersion: v1
      baseDomain: {{ aws_domain|default("rhods.ccitredhat.com") }}
      compute:
      - name: worker
        platform:
          openstack:
            type: {{ osp_flavor|default("g.standard.xl") }}
        replicas: 3
      controlPlane:
        name: master
        platform:
          openstack:
            type: {{ osp_flavor|default("g.standard.xl") }}
        replicas: 3
      metadata:
        name: {{ hive_cluster_name }}-install
      networking:
        clusterNetwork:
        - cidr: 10.128.0.0/14
          hostPrefix: 23
        machineNetwork:
        - cidr: 192.169.0.0/16
        networkType: OpenShiftSDN
        serviceNetwork:
        - 172.30.0.0/16
      platform:
        openstack:
          cloud: {{ osp_cloud_name|default("openstack") }}
          computeFlavor: m1.large
          externalDNS: null
          externalNetwork: {{ osp_network|default("shared_net_5") }}
      pullSecret: {{ pull_secret|default("") }}
      sshKey: {{ ssh_key|default("") }}
- apiVersion: hive.openshift.io/v1
  kind: ClusterDeploymentCustomization
  metadata:
    name: {{ hive_cluster_name }}-conf
    namespace: {{ hive_claim_ns|default("rhods") }}
  spec:
    installConfigPatches:
      - op: add
        path: /platform/openstack/apiFloatingIP
        value: {{ osp_fip_api }}
      - op: add
        path: /platform/openstack/ingressFloatingIP
        value: {{ osp_fip_apps }}
      - op: add
        path: /platform/openstack/externalNetwork
        value: {{ osp_network|default("shared_net_5") }}
      - op: add
        path: /metadata/name
        value: {{ hive_cluster_name }}
- apiVersion: v1
  kind: Secret
  metadata:
    name: {{ hive_cluster_name }}-cred
    namespace: {{ hive_claim_ns|default("rhods") }}
  type: Opaque
  data:
    clouds.yaml: {{ OSP_CRED_DECODED }}
    cloud: {{ OSP_CLOUD_DECODED }}
- apiVersion: hive.openshift.io/v1
  kind: ClusterImageSet
  metadata:
    name: rhods-imageset-ocp-{{ ocp_version }}
    namespace: {{ hive_claim_ns|default("rhods") }}
  spec:
    releaseImage: quay.io/openshift-release-dev/ocp-release:{{ ocp_version }}-x86_64